### ISSUE TITLE
libwmbus.so

### ISSUE THREAD

**Issue by CheeseRage** [ffcrg/ecpiww#1]
Hello ffcrg!
I really like your project and also want to build such a system for myself.
But I don't want to build it with a Raspberry Pi in the beginning. So when I tried to make the whole thing work I discovered the binary libwmbus.so.
Would it be possible to get the source code of that file?

**Comment by ffcrg** [comment]
Hi
the latest version uses a different API from IMST. 
The binary libwmbus.so is no more nedded.

Best regards
