### ISSUE TITLE
Download image

### ISSUE THREAD

**Issue by starcraft04** [ffcrg/ecpiww#5]
Hi,

When connected via USB, there is the ability to download the image. 

How could this be done with the raspberry via wireless M Bus? The image when downloaded via USB is 20kb so this should be feasible.

Thanks,

John.

**Comment by ffcrg** [comment]
Hi,
sending other data then the meter readings is not implemented.

The M-Bus (and also the wireless M-Bus) is used to transfer the meter readings. 
(see http://www.m-bus.com/files/w4b21021.pdf)

Downloading an image via wireless M-Bus would mean to implement a private protocol to transfer the 20kByte data package from the sender to the receiver.

Best regards
ffcrg
